.rubocop.yml:
  default_configs:
    Style/SignalException:
      Enabled: false
    Style/DoubleNegation:
      Enabled: false
    Style/MultipleComparison:
      Enabled: false
    Style/NumericPredicate:
      Enabled: false
    Style/SignalException:
      Enabled: false
    Layout/HeredocIndentation:
      Enabled: false
    Layout/LineLength:
      Enabled: false
    Metrics/BlockNesting:
      Enabled: false
    Naming/AccessorMethodName:
      Enabled: false
    Naming/PredicateName:
      Enabled: false
    RSpec/VariableName:
      Enabled: false
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 4.30'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.9'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.22'
      - gem: github_changelog_generator
      - gem: async
        version: '~> 1'
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: nokogiri

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
